### ISSUE TITLE
support for private ip filtering

### ISSUE THREAD

**Issue by dcharbonnier** [ahmadnassri/forwarded-http#1]
Most of the time we want to avoid receiving private IP it would be nice to have an option to filter then automatically.
- for ipv4 http://tools.ietf.org/html/rfc1918#section-3  
- for ipv6 http://tools.ietf.org/html/rfc4193#section-3.1

**Comment by ahmadnassri** [comment]
good point, I'll look into that, have you came across any implementation of IP filtering that satisfies RFC IP formatting?

**Comment by dcharbonnier** [comment]
what interface do you plan for that ? I can do it but you probably have am idea about how you want the things to be done. We can add a property on the forwarded object or a static method on the class to filter a params.ips for example

**Comment by ahmadnassri** [comment]
I'm thinking this is a complex logic piece deserving of its own moduke, since you might want to do things like IP range filtering ...

it can be then included as a dependency here and its options passed as properties to the forwarded object.

**Comment by ahmadnassri** [comment]
this seems to do the trick: https://www.npmjs.com/package/ip-filter thoughts?

**Comment by dcharbonnier** [comment]
so with a version 0.0.1 it may be the right moment to do something like :

```
var forwarded = require('forwarded-http')
var params = forwarded.parse(req)
var ips = forwarded.filter(params.ips, {
  pv4: true, // allow ipv4
  ipv6: true, // allow ipv6
 private:false // allow for private ip address
});
```

Ip filter has 100% code coverage but the syntax is very strange for filtering ip...
10.0.0.0/8 seams more natural and I'm not sure people need anything else than filtering the private ip on a project like yours.

**Comment by ahmadnassri** [comment]
@dcharbonnier implemented in https://github.com/ahmadnassri/forwarded-http/commit/629c947d01662e15848b7ac00a06e77d8b7aeeae

let me know if you have any feedback, so I can close this issue

**Comment by dcharbonnier** [comment]
nice but I don't see the utility of 'positive' filtering, it looks hard this way to return only valid public ip

**Comment by ahmadnassri** [comment]
it also supports 'negative' by prefixing `!` to the pattern. unless you mean something else, can you further clarify with an example plz?

as for "validity", there's nothing in `RFC2379` that dictates the `for` parameter to be an IP ... it can be, but its not limited to IP values ...

I could however, filter out the `.ips` property to include IPs (v4, v6) **only** since that's what the name implies.

**Comment by ahmadnassri** [comment]
0f474af969cce68c1dcf634833a4f61e7a35aaa7 now filters out any invalid IPs from the `.ips` array.

also, built [`ip-port-regex`](https://github.com/ahmadnassri/ip-port-regex) as companion/dependency module
